Database Branch
rpi-dotcio/phpLicenseWatcher pull request #43
Opened 2020-12-04 19:27 UTC by pbailie

New DB schema
Remove pear dependencies
Refactor code
Bugfixes

Close #8 
Close #11 
Close #22 
Close #25 
Close #26 
Close #29 
Close #30 
Close #32 
Close #35 
Close #36 
Close #38 
Close #39 
Close #40 
Close #42

2020-12-09 14:38 UTC, mcglow2 requested changes
Looks good for most part.  Lets go with  #efefef for alternating table row background color.  Do in css not inline.

I also noticed that usage.php errors when empty, ie all 'show_in_lists = 0' .  Also check that index.php doesnt error if there are not servers yet.

2020-12-09 15:15 UTC, pbailie commented
@mcglow2 
Have you gotten a specific error message in `index.php` when there are no servers?  (I have not in my testing).

2020-12-09 17:23 UTC, mcglow2 commented
I did not observe error on index.php, just wanted to have you check it.  So if you don't see one its probably fine.

2020-12-10 18:53 UTC, mcglow2 approved these changes

2020-12-10 18:54 UTC, merged